=== mikyll/Cluedo/Progettazione/Persistenza/CarteIndizio.xsd
<?xml version="1.0" encoding="utf-8" ?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:simpleType name="descrizioneType">
		<xs:restriction base="xs:string">
			<xs:minLength value="4" />
			<xs:maxLength value="24" />
			<xs:pattern value="[a-zA-Z\s]*" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="tipoCartaType">
		<xs:restriction base="xs:string">
			<xs:pattern value="(stanza|arma|sospettato)" />
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="immagineType">
		<xs:sequence>
			<xs:element name="imageLocation" type="xs:anyURI"/>
		</xs:sequence>
		<xs:attribute name="dpi" type="xs:integer" use="optional"/>
		<xs:attribute name="languageOfImage" type="xs:language" use="optional"/>
	</xs:complexType>
	<xs:complexType name="cartaIndizioType">
		<xs:sequence>
			<xs:element name="descrizione" type="descrizioneType"/>
			<xs:element name="tipoCarta" type="tipoCartaType"/>
			<xs:element name="immagine" type="immagineType" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>	
	
	
	<xs:element name="carteIndizio">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="cartaIndizio" type="cartaIndizioType" minOccurs="21" maxOccurs="23"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== mikyll/Cluedo/Progettazione/Persistenza/CarteIndizio.xml
<?xml version="1.0" encoding="utf-8" ?>

<carteIndizio xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="CarteIndizio.xsd">
<cartaIndizio>
	<descrizione>Cucina</descrizione>
	<tipoCarta>stanza</tipoCarta>
</cartaIndizio>
<cartaIndizio>
	<descrizione>Ingresso</descrizione>
	<tipoCarta>stanza</tipoCarta>
</cartaIndizio>
<cartaIndizio>
	<descrizione>Libreria</descrizione>
	<tipoCarta>stanza</tipoCarta>
</cartaIndizio>
<cartaIndizio>
	<descrizione>Sala da Ballo</descrizione>
	<tipoCarta>stanza</tipoCarta>
</cartaIndizio>
<cartaIndizio>
	<descrizione>Sala da Pranzo</descrizione>
	<tipoCarta>stanza</tipoCarta>
</cartaIndizio>
<cartaIndizio>
	<descrizione>Sala giochi</descrizione>
	<tipoCarta>stanza</tipoCarta>
</cartaIndizio>
<cartaIndizio>
	<descrizione>Salotto</descrizione>
	<tipoCarta>stanza</tipoCarta>
</cartaIndizio>
<cartaIndizio>
	<descrizione>Serra</descrizione>
	<tipoCarta>stanza</tipoCarta>
</cartaIndizio>
<cartaIndizio>
	<descrizione>Studio</descrizione>
	<tipoCarta>stanza</tipoCarta>
</cartaIndizio>

<cartaIndizio>
	<descrizione>Candeliere</descrizione>
	<tipoCarta>arma</tipoCarta>
</cartaIndizio>
<cartaIndizio>
	<descrizione>Chiave Inglese</descrizione>
	<tipoCarta>arma</tipoCarta>
</cartaIndizio>
<cartaIndizio>
	<descrizione>Corda</descrizione>
	<tipoCarta>arma</tipoCarta>
</cartaIndizio>
<cartaIndizio>
	<descrizione>Pugnale</descrizione>
	<tipoCarta>arma</tipoCarta>
</cartaIndizio>
<cartaIndizio>
	<descrizione>Piede di Porco</descrizione>
	<tipoCarta>arma</tipoCarta>
</cartaIndizio>
<cartaIndizio>
	<descrizione>Pistola</descrizione>
	<tipoCarta>arma</tipoCarta>
</cartaIndizio>
<cartaIndizio>
	<descrizione>Veleno</descrizione>
	<tipoCarta>arma</tipoCarta>
</cartaIndizio>

<cartaIndizio>
	<descrizione>Kassandra Scarlet</descrizione>
	<tipoCarta>sospettato</tipoCarta>
</cartaIndizio>
<cartaIndizio>
	<descrizione>Diane White</descrizione>
	<tipoCarta>sospettato</tipoCarta>
</cartaIndizio>
<cartaIndizio>
	<descrizione>Dottoressa Orchid</descrizione>
	<tipoCarta>sospettato</tipoCarta>
</cartaIndizio>
<cartaIndizio>
	<descrizione>Eleanor Peacock</descrizione>
	<tipoCarta>sospettato</tipoCarta>
</cartaIndizio>
<cartaIndizio>
	<descrizione>Jack Mustard</descrizione>
	<tipoCarta>sospettato</tipoCarta>
</cartaIndizio>
<cartaIndizio>
	<descrizione>Jacob Green</descrizione>
	<tipoCarta>sospettato</tipoCarta>
</cartaIndizio>
<cartaIndizio>
	<descrizione>Victor Plum</descrizione>
	<tipoCarta>sospettato</tipoCarta>
</cartaIndizio>

</carteIndizio>
