=== mikyll/Cluedo/Progettazione/Persistenza/Personaggi.xsd
<?xml version="1.0" encoding="utf-8" ?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:simpleType name="nomeType">
		<xs:restriction base="xs:string">
			<xs:minLength value="7" />
			<xs:maxLength value="24" />
			<xs:pattern value="[a-zA-Z\s]*" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="coloreType">
		<xs:restriction base="xs:string">
			<xs:pattern value="(rosso|viola|giallo|verde|bianco|blu)" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="descrizioneType">
		<xs:restriction base="xs:string">
			<xs:minLength value="20" />
			<xs:maxLength value="124" />
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="immagineType">
		<xs:sequence>
			<xs:element name="imageLocation" type="xs:anyURI"/>
		</xs:sequence>
		<xs:attribute name="dpi" type="xs:integer" use="optional"/>
		<xs:attribute name="languageOfImage" type="xs:language" use="optional"/>
	</xs:complexType>
	
	<xs:complexType name="personaggioType">
		<xs:sequence>
			<xs:element name="nome" type="nomeType"/>
			<xs:element name="colore" type="coloreType"/>
			<xs:element name="descrizione" type="descrizioneType"/>
			<xs:element name="immagine" type="immagineType"/>
		</xs:sequence>
	</xs:complexType>	
	
	
	<xs:element name="personaggi">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="personaggio" type="personaggioType" minOccurs="6" maxOccurs="6"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== mikyll/Cluedo/Progettazione/Persistenza/Personaggi.xml
<?xml version="1.0" encoding="utf-8" ?>

<personaggi xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Personaggi.xsd">

	<personaggio>
		<nome>Kassandra Scarlet</nome>
		<colore>rosso</colore>
		<descrizione>Donna seducente sempre al centro del gossip</descrizione>
		<immagine>
			<imageLocation>images/personaggi/pg1.png</imageLocation>
		</immagine>
	</personaggio>	

	<personaggio>
		<nome>Victor Plum</nome>
		<colore>viola</colore>
		<descrizione>Giovane informatico sviluppatore di videogames</descrizione>
		<immagine>
			<imageLocation>images/personaggi/pg2.png</imageLocation>
		</immagine>
	</personaggio>
	<personaggio>
		<nome>Jack Mustard</nome>
		<colore>giallo</colore>
		<descrizione>Telecronista con un glorioso passato da calciatore</descrizione>
		<immagine>
			<imageLocation>images/personaggi/pg3.png</imageLocation>
		</immagine>
	</personaggio>
	<personaggio>
		<nome>Jacob Green</nome>
		<colore>verde</colore>
		<descrizione>Uomo molto influente ma con il quale non è prudente restare in debito</descrizione>
		<immagine>
			<imageLocation>images/personaggi/pg4.png</imageLocation>
		</immagine>
	</personaggio>
	<personaggio>
		<nome>Diane White</nome>
		<colore>bianco</colore>
		<descrizione>Donna con infanzia d'attrice che vuole attirare nuovamente l'attenzione su di sé</descrizione>
		<immagine>
			<imageLocation>images/personaggi/pg5.png</imageLocation>
		</immagine>
	</personaggio>
	<personaggio>
		<nome>Eleanor Peacock</nome>
		<colore>blu</colore>
		<descrizione>Discendente di un'agiata famiglia di politici, fissata con la perfezione</descrizione>
		<immagine>
			<imageLocation>images/personaggi/pg6.png</imageLocation>
		</immagine>
	</personaggio>
	
</personaggi>
