=== mikyll/Cluedo/Progettazione/Persistenza/Utenti.xsd
<?xml version="1.0" encoding="utf-8" ?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:simpleType name="usernameType">
		<xs:restriction base="xs:string">
			<xs:minLength value="4" />
			<xs:maxLength value="16" />
			<xs:pattern value="[a-zA-Z0-9\-_]*" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="passwordType">
		<xs:restriction base="xs:string">
			<xs:minLength value="8" />
			<xs:maxLength value="32" />
			<xs:pattern value="[a-zA-Z0-9!?,.@#\-_]*" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="emailType">
		<xs:restriction base="xs:string">
			<xs:maxLength value="254" />
			<xs:pattern value="[a-zA-Z0-9]([-.\w]*[a-zA-Z0-9])*@([a-zA-Z0-9][-\w]*[a-zA-Z0-9]\.)+[a-zA-Z]{2,9}" />
		</xs:restriction>
	</xs:simpleType>
	
	<xs:complexType name="utenteType">
		<xs:sequence>
			<xs:element name="username" type="usernameType"/>
			<xs:element name="password" type="passwordType"/>
			<xs:element name="email" type="emailType"/>
		</xs:sequence>
	</xs:complexType>	
	
	
	<xs:element name="utenti">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="utente" type="utenteType" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== mikyll/Cluedo/Progettazione/Persistenza/Utenti.xml
<?xml version="1.0" encoding="utf-8" ?>

<utenti xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Utenti.xsd">

	<utente>
		<username>Sm4tt_404</username>
		<password>password404</password>
		<email>sm4tt404@gmail.com</email>
	</utente>
	<utente>
		<username>Eugenio73</username>
		<password>ciao.123@#</password>
		<email>eugenio73@unibo.it</email>
	</utente>
	<utente>
		<username>Mario31</username>
		<password>Mario1331</password>
		<email>mario.rossi31@hotmail.en</email>
	</utente>

</utenti>
